#!/usr/bin/env bash

# Useful methods.
#
set_variable () { export $1="$2"; echo "export $1=\"$2\""; }
unset_variable () { echo "unset $1"; }

path_append ()  { path_remove $1; set_variable PATH "$PATH:$1"; }
path_prepend () { path_remove $1; set_variable PATH "$1:$PATH"; }
path_remove ()  { set_variable PATH `echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }

command_exists () { type "$1" &> /dev/null; }

warn () { echo "$1" >&2; }
halt () { warn "$1"; exit 1; }

# A bunch of useful variables.
#
RBFU_ROOT="$HOME/.rbfu"
